spin_manifest_version = 2

[application]
name = "moonbit-server"
version = "1.0.0"
description = "A simple application."

[variables]
api_key = { required = true, secret = true }

# The application's sole trigger.
[[trigger.http]]
route = "/"
component = "server"

[component.server]
description = "A simple server."
# The Wasm module to run for the component
source = "target/server.wasm"
# Environment variable
allowed_outbound_hosts = ["https://openrouter.ai"]

# How to build the Wasm module from source
[component.server.build]
command = """
  moon build --target wasm
  wasm-tools component embed --encoding utf16 wit target/wasm/release/build/http-server.wasm -o target/server.core.wasm
  wasm-tools component new target/server.core.wasm -o target/server.wasm
"""

[component.server.variables]
openai_api_key="{{ api_key }}"
